spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Grupo-23-BDD-OO2-2021
    username: root
    password: newVegas2202#
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNaming.Strategy
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false